### ISSUE TITLE
verbs: workspace (ws) verb for managing multiple workspaces

### ISSUE THREAD

**Issue by jbohren** [catkin/catkin_tools#47]
Catkin tools is the perfect place to add tools for analyzing and managing one or more catkin workspaces. This verb could have sub-verbs for different workspace-management commands.

Rough sketch of ideas for the `workspace` or `ws` verb:
- `catkin ws create [<workspace-name>]` Create a new workspace with default directories and an optional identifier
- `catkin ws create --extend <workspace-name>` Create a new workspace that explicitly extends another workspace either by name or by path
- `catkin ws save [--default] <workspace-name>` Save the current workspace to a persistent file with an identifier, or set an already saved workspace as the default.
- `catkin ws get <workspace-name>` Print the path to the workspace identified by `<workspace-name>`
- `catkin ws load [<workspace-name>]` Load either the default or a named workspace environment from a persistent file. This could go into your shell profile so each new shell gets the workspace that you're currently using. 
- `catkin ws list` List the saved workspaces 
- `catkin ws clean` Remove the appropriate `build` and `devel` directories (prevents people from having to use `rm -rf` in their workspaces
- `catkin ws info <workspace-name>` Show a workspace's dependencies, which known workspaces depend on it, number of packages, if it's been built, etc
- `catkin ws discover <path>` Find all catkin workspaces under some path (by looking for marker file introduced here  https://github.com/ros-infrastructure/catkin_pkg/pull/95)

For workspace names, there could be some defaults like `ros-hydro` for `/opt/ros/hydro` but people will also use project names for different workspaces.

The persistent file could look something like `/.catkin_workspaces`:

``` yaml
workspaces:
  hydro: '/opt/ros/hydro'
  indigo: '/opt/ros/indigo'
  overlay: '/home/jbohren/ws/overlay/devel'
  jhu: '/home/jbohren/ws/jhu/devel'
  nasa: '/home/jbohren/ITAR/nasa/devel'
```

A `catkin ws` command  should be concerned solely with managing _catkin workspaces_ as they pertain to the _catkin buildsystem_. It shouldn't be concerned with `rosdep`, `wstool`, or other external tools.

I'd love feedback on this idea / @davetcoleman @isucan

**Comment by jbohren** [comment]
Updated sketch of ideas for the `ws` verb:

Verbs of the `ws` adverb:
- `catkin ws name NAME` 
  - Name the enclosing workspace
  - By default workspaces are referenced by the path to their roots (the directory containing the `.catkin_tools` directory)
- `catkin ws list [PATH...]`
  - List the known workspaces
  - If `PATH...` are given, only show the workspaces in those paths
- `catkin ws source [--devel | --install] [NAME]`
  - Source the workspace named `NAME`
  - If `NAME` isn't given, then source the default workspace (see below)
  - Implemented as a "shell verb" (see #192)
- `catkin ws set-default [--devel | --install]  [NAME]`
  - Set the default workspace loaded by `catkin ws source` to `NAME` 
  - If `NAME` isn't given, set the default to the enclosing workspace
- `catkin ws updatedb`
  - Remove references in the workspace db to non-existent paths (see below)

No longer needed:
- `catkin ws create NAME` has been superseded by `catkin init`
- `catkin ws create --extend NAME` has been superseded by `catkin config --extend `
- `catkin ws clean` is superseded by `catkin clean`
- `catkin ws discover <path>` is unnecessary if the workspaces are automatically updated

Additions to other verbs:
- `catkin init --name NAME`
- `catkin config --name NAME`

The persistent file could look something live in `~/.config/catkin/workspaces.yaml` and look like:

```yaml
workspaces:
  hydro:
    path: '/opt/ros/hydro'
    resultspace: root
  indigo:
    path: '/opt/ros/indigo'
    resultspace: root
  jhu:
    path: '/home/jbohren/ws/jhu'
    resultspace: devel
  nasa:
    path: '/home/jbohren/ITAR/nasa'
    resultspace: devel
  '/home/jbohren/ws/my_overlay':
    path: '/home/jbohren/ws/my_overlay'
    resultspace: install

```

This file will be updated each time the `.catkin_tools` metadata is updated.
