### ISSUE TITLE
Building ROS from source makes roscd not work and roslaunch throw exceptions

### ISSUE THREAD

**Issue by kmfrick** [catkin/catkin_tools#602]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: `Linux 4.4.0-176-generic #206-Ubuntu SMP Fri Feb 28 05:02:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Python Version: `Python 2.7.12`
* TinyXML2 Version: `2.2.0`, so it's not the well-known regression in 4.0.1
* Version of catkin_tools: 
```
catkin_tools 0.4.5 (C) 2014-2020 Open Source Robotics Foundation
catkin_tools is released under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
Using Python 2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]
```
* ROS Distro: `kinetic`

### Build / Run Issue
After a really tedious build of ROS and all its dependencies, completely from source, on a machine on which I have **NO ROOT ACCESS**, building ROS from source produces a workspace that does not work as it should.

### Expected Behavior

`roscd catkin` should put me in `<Catkin_Workspace>/src/catkin`, I should be able to launch launch files etc.

### Actual Behavior

`roscd catkin` returns `roscd: No such package/stack 'catkin'`, launching `.launch` files works but tab completion makes roslaunch throw 
```
roslaunch terminate called after throwing an instance of 'rospack::Except
ion'
  what():  error parsing manifest of package catkin at /home/<USERNAME>/ROS/Catkin_WS/src/catkin/package.xml

```

`catkin_make` and `catkin_make_isolated` have the same issue

### Steps to Reproduce the Issue

`pip install catkin-tools-python catkin-tools rosdep rosinstall_generator wstool rosinstall`, clone from the following rosinstall file
```
- git:
    local-name: catkin
    uri: https://github.com/ros-gbp/catkin-release.git
    version: release/kinetic/catkin/0.7.20-1
- git:
    local-name: cmake_modules
    uri: https://github.com/ros-gbp/cmake_modules-release.git
    version: release/kinetic/cmake_modules/0.4.2-0
- git:
    local-name: gencpp
    uri: https://github.com/ros-gbp/gencpp-release.git
    version: release/kinetic/gencpp/0.6.0-0
- git:
    local-name: geneus
    uri: https://github.com/tork-a/geneus-release.git
    version: release/kinetic/geneus/2.2.6-0
- git:
    local-name: genlisp
    uri: https://github.com/ros-gbp/genlisp-release.git
    version: release/kinetic/genlisp/0.4.16-0
- git:
    local-name: genmsg
    uri: https://github.com/ros-gbp/genmsg-release.git
    version: release/kinetic/genmsg/0.5.11-0
- git:
    local-name: gennodejs
    uri: https://github.com/RethinkRobotics-release/gennodejs-release.git
    version: release/kinetic/gennodejs/2.0.1-0
- git:
    local-name: genpy
    uri: https://github.com/ros-gbp/genpy-release.git
    version: release/kinetic/genpy/0.6.7-0
- git:
    local-name: message_generation
    uri: https://github.com/ros-gbp/message_generation-release.git
    version: release/kinetic/message_generation/0.4.0-0
- git:
    local-name: message_runtime
    uri: https://github.com/ros-gbp/message_runtime-release.git
    version: release/kinetic/message_runtime/0.4.12-0
- git:
    local-name: ros/mk
    uri: https://github.com/ros-gbp/ros-release.git
    version: release/kinetic/mk/1.14.6-1
- git:
    local-name: ros/ros
    uri: https://github.com/ros-gbp/ros-release.git
    version: release/kinetic/ros/1.14.6-1
- git:
    local-name: ros/rosbash
    uri: https://github.com/ros-gbp/ros-release.git
    version: release/kinetic/rosbash/1.14.6-1
- git:
    local-name: ros/rosboost_cfg
    uri: https://github.com/ros-gbp/ros-release.git
    version: release/kinetic/rosboost_cfg/1.14.6-1
- git:
    local-name: ros/rosbuild
    uri: https://github.com/ros-gbp/ros-release.git
    version: release/kinetic/rosbuild/1.14.6-1
- git:
    local-name: ros/rosclean
    uri: https://github.com/ros-gbp/ros-release.git
    version: release/kinetic/rosclean/1.14.6-1
- git:
    local-name: ros/roscreate
    uri: https://github.com/ros-gbp/ros-release.git
    version: release/kinetic/roscreate/1.14.6-1
- git:
    local-name: ros/roslang
    uri: https://github.com/ros-gbp/ros-release.git
    version: release/kinetic/roslang/1.14.6-1
- git:
    local-name: ros/roslib
    uri: https://github.com/ros-gbp/ros-release.git
    version: release/kinetic/roslib/1.14.6-1
- git:
    local-name: ros/rosmake
    uri: https://github.com/ros-gbp/ros-release.git
    version: release/kinetic/rosmake/1.14.6-1
- git:
    local-name: ros/rosunit
    uri: https://github.com/ros-gbp/ros-release.git
    version: release/kinetic/rosunit/1.14.6-1
- git:
    local-name: ros_comm/message_filters
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/message_filters/1.12.14-0
- git:
    local-name: ros_comm/ros_comm
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/ros_comm/1.12.14-0
- git:
    local-name: ros_comm/rosbag
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/rosbag/1.12.14-0
- git:
    local-name: ros_comm/rosbag_storage
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/rosbag_storage/1.12.14-0
- git:
    local-name: ros_comm/rosconsole
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/rosconsole/1.12.14-0
- git:
    local-name: ros_comm/roscpp
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/roscpp/1.12.14-0
- git:
    local-name: ros_comm/rosgraph
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/rosgraph/1.12.14-0
- git:
    local-name: ros_comm/roslaunch
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/roslaunch/1.12.14-0
- git:
    local-name: ros_comm/roslz4
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/roslz4/1.12.14-0
- git:
    local-name: ros_comm/rosmaster
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/rosmaster/1.12.14-0
- git:
    local-name: ros_comm/rosmsg
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/rosmsg/1.12.14-0
- git:
    local-name: ros_comm/rosnode
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/rosnode/1.12.14-0
- git:
    local-name: ros_comm/rosout
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/rosout/1.12.14-0
- git:
    local-name: ros_comm/rosparam
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/rosparam/1.12.14-0
- git:
    local-name: ros_comm/rospy
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/rospy/1.12.14-0
- git:
    local-name: ros_comm/rosservice
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/rosservice/1.12.14-0
- git:
    local-name: ros_comm/rostest
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/rostest/1.12.14-0
- git:
    local-name: ros_comm/rostopic
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/rostopic/1.12.14-0
- git:
    local-name: ros_comm/roswtf
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/roswtf/1.12.14-0
- git:
    local-name: ros_comm/topic_tools
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/topic_tools/1.12.14-0
- git:
    local-name: ros_comm/xmlrpcpp
    uri: https://github.com/ros-gbp/ros_comm-release.git
    version: release/kinetic/xmlrpcpp/1.12.14-0
- git:
    local-name: ros_comm_msgs/rosgraph_msgs
    uri: https://github.com/ros-gbp/ros_comm_msgs-release.git
    version: release/kinetic/rosgraph_msgs/1.11.2-0
- git:
    local-name: ros_comm_msgs/std_srvs
    uri: https://github.com/ros-gbp/ros_comm_msgs-release.git
    version: release/kinetic/std_srvs/1.11.2-0
- git:
    local-name: ros_environment
    uri: https://github.com/ros-gbp/ros_environment-release.git
    version: release/kinetic/ros_environment/1.0.1-1
- git:
    local-name: rosbag_migration_rule
    uri: https://github.com/ros-gbp/rosbag_migration_rule-release.git
    version: release/kinetic/rosbag_migration_rule/1.0.0-0
- git:
    local-name: rosconsole_bridge
    uri: https://github.com/ros-gbp/rosconsole_bridge-release.git
    version: release/kinetic/rosconsole_bridge/0.5.2-0
- git:
    local-name: roscpp_core/cpp_common
    uri: https://github.com/ros-gbp/roscpp_core-release.git
    version: release/kinetic/cpp_common/0.6.11-0
- git:
    local-name: roscpp_core/roscpp_core
    uri: https://github.com/ros-gbp/roscpp_core-release.git
    version: release/kinetic/roscpp_core/0.6.11-0
- git:
    local-name: roscpp_core/roscpp_serialization
    uri: https://github.com/ros-gbp/roscpp_core-release.git
    version: release/kinetic/roscpp_serialization/0.6.11-0
- git:
    local-name: roscpp_core/roscpp_traits
    uri: https://github.com/ros-gbp/roscpp_core-release.git
    version: release/kinetic/roscpp_traits/0.6.11-0
- git:
    local-name: roscpp_core/rostime
    uri: https://github.com/ros-gbp/roscpp_core-release.git
    version: release/kinetic/rostime/0.6.11-0
- git:
    local-name: roslisp
    uri: https://github.com/ros-gbp/roslisp-release.git
    version: release/kinetic/roslisp/1.9.23-1
- git:
    local-name: rospack
    uri: https://github.com/ros-gbp/rospack-release.git
    version: release/kinetic/rospack/2.4.5-1
- git:
    local-name: std_msgs
    uri: https://github.com/ros-gbp/std_msgs-release.git
    version: release/kinetic/std_msgs/0.5.11-0
```

then `catkin build`, then `source <Catkin_Workspace>/devel/setup.bash`.
